### ISSUE TITLE
What do you want to do next pattern

### ISSUE THREAD

**Issue by peteblakemore** [SkillsFundingAgency/das-design-system#22]
What
Currently there are two patterns being used across the service for offering options for next steps on confirmation pages.

Why
The radio option version is most common, but is an incorrect usage of a form (we don't collect data on the selection). The second version which should replace the form version is to offer the options in a list of links.

## Example 1

<img width="569" alt="image" src="https://user-images.githubusercontent.com/7149718/66125833-e5f4bc80-e5df-11e9-8546-7afc3c958075.png">

## Example 2

<img width="563" alt="image" src="https://user-images.githubusercontent.com/7149718/66126023-556aac00-e5e0-11e9-8ce6-ded7489455ec.png">

What evidence do you have that it's needed by multiple services across government?
What evidence do you have that it meets the needs of the users of those services?
Have you checked that it doesn't already exist in the GOV.UK Design System?

Anything else
Include links to any examples, research or code to support your proposal, if available.

**Comment by JaskiranKang** [comment]
> What
> Currently there are two patterns being used across the service for offering options for next steps on confirmation pages.
> 
> Why
> The radio option version is most common, but is an incorrect usage of a form (we don't collect data on the selection). The second version which should replace the form version is to offer the options in a list of links.
> 
> ## Example 1
> <img alt="image" width="569" src="https://user-images.githubusercontent.com/7149718/66125833-e5f4bc80-e5df-11e9-8546-7afc3c958075.png">
> 
> ## Example 2
> <img alt="image" width="563" src="https://user-images.githubusercontent.com/7149718/66126023-556aac00-e5e0-11e9-8ce6-ded7489455ec.png">
> 
> What evidence do you have that it's needed by multiple services across government?
> What evidence do you have that it meets the needs of the users of those services?
> Have you checked that it doesn't already exist in the GOV.UK Design System?
> 
> Anything else
> Include links to any examples, research or code to support your proposal, if available.

**Comment by JaskiranKang** [comment]
More Research needed? @peteblakemore do you have any supporting material?

**Comment by peteblakemore** [comment]
@JaskiranKang I don't, mainly because we're pushed to use the radio pattern because it's prevalent across the service. There's never been an apetite to change it that I've seen.
