### ISSUE TITLE
Create DAS Design system email address

### ISSUE THREAD

**Issue by sensecall** [SkillsFundingAgency/das-design-system#5]

**Comment by JaskiranKang** [comment]
Requested

**Comment by JaskiranKang** [comment]
dasdesignsystem@digital.education.gov.uk created

**Comment by sensecall** [comment]
https://github.com/SkillsFundingAgency/das-design-system/commit/9baa5e9f5fab4ec3d2fc3b6bd9ad35b8c71e8cfd
